#print(" my name is :- Jayesh Dagesing Magar")
print("college :- K.K. wagh polytechnic , Nashik")
print("Adderess :- Aghar kh Tal: Malegaon ,Nashik")
print("Age : 18")
a=int(input("Value of a"))
b=int(input("Value of b"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
