a =int(input("Enter value of a :"))
b =int(input("Enter value of b :"))
print(f"Addition of {a} and {b} is :",(a+b))
print(f"Subtraction of {a} and {b} is :",(a-b))
print(f"Multiplicatin of {a} and {b} is :",(a*b))
print(f"Division of {a} and {b} is :",(a/b))
print(f"Floor Division of {a} and {b} is :",(a//b))
print(f"Module of {a} and {b} is :",(a%b))
print(f"Power of {a} and {b} is :",(a**b))