print(" Name :- Jayesh Dagesing Magar")
print("Class : TYCM")
print("Branch : Computer technology")
print("Age : 18")
print("""College :- K.K. wagh polytechnic \t Amruthdham \t Nashik \t Maharashtra""")
print("Age : 18")
print(""" Address: aghar \t Malegaon \t Nashik""")

print("print this statement:\n\tFeatures of Python:")

print(" 1. Easy to Learn and Use\n\t - Simple syntax similar to English")    
print("2. Interpreted Language\n\t   - Executes code line by line")  
print(" 3. Dynamically Typed\n\t- No need to declare variable types")
print("4. Extensive Libraries\n\t  - Supports many built-in and third-party libraries") 
print("5. Portable \n\t  - Runs on different platforms without changes")    
print("6. Object-Oriented\n\t- Supports classes and objects")    
print("7. Open Source \n\t- Free to use and distribute")
print(" 8. High-level Language \n\t- Abstracts complex details from the programmer")
print("Start exploring Python today!")
